tasks/urls.py
from django.urls import path

from tasks.views import (
    index,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerDeleteView,
    toggle_task_status
)

urlpatterns = [
    path("", index, name="index"),
    path("positions/", PositionListView.as_view(), name="position-list"),
    path("positions/create/", PositionCreateView.as_view(), name="position-create"),
    path("positions/<int:pk>/update/", PositionUpdateView.as_view(), name="position-update"),
    path("positions/<int:pk>/delete/", PositionDeleteView.as_view(), name="position-delete"),
    path("task-types/", TaskTypeListView.as_view(), name="task-type-list"),
    path("task-types/create/", TaskTypeCreateView.as_view(), name="task-type-create"),
    path("task-types/<int:pk>/update/", TaskTypeUpdateView.as_view(), name="task-type-update"),
    path("task-types/<int:pk>/delete/", TaskTypeDeleteView.as_view(), name="task-type-delete"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("workers/<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("workers/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("tasks/<int:task_id>/toggle-status/", toggle_task_status, name="toggle-task-status"),
]

app_name = "tasks"

tasks/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Position(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class TaskType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(
        Position,
        related_name="workers",
        on_delete=models.SET_NULL,
        null=True
    )

    def get_absolute_url(self):
        return reverse("tasks:worker-detail", kwargs={"pk": self.pk})

class Task(models.Model):
    PRIORITY_CHOICES = [
        ("High", "High"),
        ("Urgent", "Urgent"),
        ("Medium", "Medium"),
        ("Low", "Low"),
    ]

    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(
        max_length=6,
        choices=PRIORITY_CHOICES,
        default="Low"
    )
    task_type = models.ForeignKey(
        TaskType,
        related_name="tasks",
        on_delete=models.CASCADE
    )
    assignees = models.ManyToManyField(Worker, related_name="assigned_tasks")

    class Meta:
        ordering = ["is_completed", "-priority", "-deadline", ]

tasks/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from tasks.models import Worker, Position, Task, TaskType


class WorkerCreationForm(UserCreationForm):
    position = forms.ModelChoiceField(
        queryset=Position.objects.all(),
        widget=forms.Select(attrs={"class": "form-control"}),
    )

    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "username",
            "password1",
            "password2",
            "first_name",
            "last_name",
            "email",
            "position"
        )

        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "first_name": forms.TextInput(attrs={"class": "form-control"}),
            "last_name": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.EmailInput(attrs={"class": "form-control"}),
        }


class WorkerUpdateForm(forms.ModelForm):
    position = forms.ModelChoiceField(
        queryset=Position.objects.all(),
        widget=forms.Select(attrs={"class": "form-control"}),
    )

    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
        required=False,
        label="New password"
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
        required=False,
        label="Confirm new password"
    )

    class Meta:
        model = Worker
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "position"
        ]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "first_name": forms.TextInput(attrs={"class": "form-control"}),
            "last_name": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.EmailInput(attrs={"class": "form-control"}),
        }


class TaskCreationForm(forms.ModelForm):
    deadline = forms.DateTimeField(
        widget=forms.DateTimeInput(
            attrs={
                "type": "datetime-local",
                "placeholder": "YYYY-MM-DD HH:MM",
                "class": "form-control",
            },
            format="%Y-%m-%dT%H:%M",
        ),
        required=False,
    )

    task_type = forms.ModelChoiceField(
        queryset=TaskType.objects.all(),
        widget=forms.Select(attrs={"class": "form-control"}),
    )

    assignees = forms.ModelMultipleChoiceField(
        queryset=Worker.objects.select_related("position").all(),
        widget=forms.CheckboxSelectMultiple(attrs={"class": "form-check-input"}),
    )

    class Meta:
        model = Task
        fields = "__all__"
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "description": forms.Textarea(attrs={"class": "form-control", "rows": 3}),
            "priority": forms.Select(attrs={"class": "form-control"}),
        }


class TaskUpdateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = "__all__"
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "description": forms.Textarea(attrs={"class": "form-control", "rows": 3}),
            "deadline": forms.DateTimeInput(
                attrs={"type": "datetime-local", "class": "form-control"}
            ),
            "priority": forms.Select(attrs={"class": "form-control"}),
            "task_type": forms.Select(attrs={"class": "form-control"}),
            "assignees": forms.CheckboxSelectMultiple(
                attrs={"class": "form-check-input"}
            ),
        }


class PositionCreationForm(forms.ModelForm):
    class Meta:
        model = Position
        fields = ["name"]
        widgets = {
            "name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter position name"}
            ),
        }


class TaskTypeCreationForm(forms.ModelForm):
    class Meta:
        model = TaskType
        fields = ["name"]
        widgets = {
            "name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter task type name"}
            ),
        }

tasks/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic

from tasks.forms import WorkerCreationForm, WorkerUpdateForm, TaskCreationForm, TaskUpdateForm
from tasks.models import Position, TaskType, Task, Worker


@login_required
def index(request: HttpRequest) -> HttpResponse:
    tasks = Task.objects.select_related("task_type").prefetch_related("assignees")

    search_queryset = request.GET.get("search", "")
    if search_queryset:
        tasks = tasks.filter(name__icontains=search_queryset)

    paginator = Paginator(tasks, 5)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    return render(
        request,
        "tasks/index.html",
        {"page_obj": page_obj, "search_queryset": search_queryset}
    )


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    paginate_by = 5

class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("tasks:position-list")
    template_name = "tasks/position_form.html"


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("tasks:position-list")
    template_name = "tasks/position_form.html"


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("tasks:position-list")


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    paginate_by = 5


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("tasks:task-type-list")
    template_name = "tasks/task_type_form.html"


class TaskTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("tasks:task-type-list")
    template_name = "tasks/task_type_form.html"


class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    success_url = reverse_lazy("tasks:task-type-list")


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskCreationForm
    success_url = reverse_lazy("tasks:index")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskUpdateForm
    success_url = reverse_lazy("tasks:index")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("tasks:index")


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    paginate_by = 5

    def get_queryset(self):
        queryset = Worker.objects.select_related("position")
        return queryset


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker


class WorkerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Worker
    form_class = WorkerCreationForm
    success_url = reverse_lazy("tasks:worker-list")


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerUpdateForm
    success_url = reverse_lazy("tasks:worker-list")


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("tasks:worker-list")


def toggle_task_status(request: HttpRequest, task_id: int) -> HttpResponse:
    task = get_object_or_404(Task, id=task_id)

    task.is_completed = not task.is_completed
    task.save()

    return redirect("tasks:index")

templates/tasks/index.html
{% extends "base.html" %}

{% block content %}
  <div class="content">
    <h2 class="content-title">Task List</h2>

    <div class="d-flex justify-content-between align-items-center mb-3">
      <form method="get" action="{% url 'tasks:index' %}" class="search-form flex-grow-1 me-3">
        <input type="text" name="search" placeholder="Search tasks..." value="{{ search_queryset }}"
               class="search-input">
        <button type="submit" class="search-button">🔍</button>
      </form>
      <a href="{% url 'tasks:task-create' %}" class="btn btn-primary btn-sm" style="white-space: nowrap;">
        Add
      </a>
    </div>

    <table class="task-table">
      <colgroup>
        <col style="width: 15%;"> <!-- Name -->
        <col style="width: 20%;"> <!-- Description -->
        <col style="width: 10%;"> <!-- Deadline -->
        <col style="width: 10%;"> <!-- Priority -->
        <col style="width: 10%;"> <!-- Task Type -->
        <col style="width: 15%;"> <!-- Assignees -->
        <col style="width: 10%;"> <!-- Completed -->
        <col style="width: 10%;"> <!-- Actions -->
      </colgroup>
      <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Deadline</th>
        <th>Priority</th>
        <th>Task Type</th>
        <th>Assignees</th>
        <th>Completed</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      {% for task in page_obj %}
        <tr>
          <td>{{ task.name }}</td>
          <td>{{ task.description|truncatechars:30 }}</td>
          <td>{{ task.deadline }}</td>
          <td><span class="priority-badge {{ task.priority|lower }}">{{ task.priority }}</span></td>
          <td>{{ task.task_type }}</td>
          <td>
            {% for assignee in task.assignees.all %}
              <span class="assignee"><a href="{% url "tasks:worker-detail" pk=assignee.id %}" style="text-decoration: none; color: white">{{ assignee.username }}</a></span>
            {% endfor %}
          </td>
          <td>
            <div class="status-container">
              <a href="{% url 'tasks:toggle-task-status' task.id %}" class="status-toggle">
                {% if task.is_completed %}
                  <span class="completed">✔️</span>
                {% else %}
                  <span class="not-completed">❌</span>
                {% endif %}
              </a>
            </div>
          </td>
          <td>
            <div class="actions-container">
              <a href="{% url 'tasks:task-update' task.id %}" class="btn btn-edit">Edit</a>
              <a href="{% url 'tasks:task-delete' task.id %}" class="btn btn-delete">Delete</a>
            </div>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/tasks/position_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="content">
    <h2 class="content-title">Delete Position</h2>
    <p>Are you sure you want to delete the position "{{ position.name }}"?</p>
    <form method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger" style="white-space: nowrap;">Yes</button>
      <a href="{% url 'tasks:position-list' %}" class="btn btn-secondary" style="white-space: nowrap;">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/tasks/position_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="content">
    <h2 class="content-title">
      {% if form.instance.pk %}
        Edit Position
      {% else %}
        Create New Position
      {% endif %}
    </h2>

    <div class="card">
      <div class="card-body">
        <form method="post" class="position-form">
          {% csrf_token %}
          
          <div class="mb-3">
            {{ form.name|as_crispy_field }}
          </div>

          <div class="d-flex justify-content-between mt-4">
            <button type="submit" class="btn btn-primary">
              {{ object|yesno:"Save,Create" }}
            </button>
            <a href="{% url 'tasks:position-list' %}" class="btn btn-secondary">Cancel</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/tasks/position_list.html
{% extends "base.html" %}

{% block content %}
  <div class="content">
    <div class="d-flex justify-content-between align-items-center mb-3">
      <h2 class="content-title">Position List</h2>
      <a href="{% url 'tasks:position-create' %}" class="btn btn-primary position-create-btn">
        Add
      </a>
    </div>

    <table class="position-table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Workers</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for position in position_list %}
          <tr>
            <td class="col-1">{{ position.name }}</td>
            <td class="col-3">
              {% if position.workers.all %}
                {% for worker in position.workers.all %}
                  <span class="position-worker-badge"><a href="{% url "tasks:worker-detail" pk=worker.id %} " style="text-decoration: none; color: white">{{ worker.username }}</a></span>
                {% endfor %}
              {% else %}
                <span class="position-no-workers">No workers</span>
              {% endif %}
            </td>
            <td class="col-1">
              <a href="{% url 'tasks:position-update' position.pk %}" class="btn btn-sm position-edit-btn">Edit</a>
              <a href="{% url 'tasks:position-delete' position.pk %}" class="btn btn-sm position-delete-btn">Delete</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/tasks/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="content">
    <h2 class="content-title">Delete Task</h2>
    <p>Are you sure you want to delete the task "{{ task.name }}"?</p>
    <form method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger" style="white-space: nowrap;">Yes</button>
      <a href="{% url 'tasks:index' %}" class="btn btn-secondary" style="white-space: nowrap;">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/tasks/task_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="content">
    <h2 class="content-title">
      {{ object|yesno:"Update,Create" }}
      Task
    </h2>

    <div class="card">
      <div class="card-body">
        <form method="post" class="task-form">
          {% csrf_token %}

          <!-- Two columns -->
          <div class="row">
            <!-- Left column -->
            <div class="col-md-6">
              <div class="mb-3">
                {{ form.name|as_crispy_field }}
              </div>

              <div class="mb-3">
                {{ form.description|as_crispy_field }}
              </div>

              <div class="mb-3">
                {{ form.deadline|as_crispy_field }}
              </div>
            </div>

            <!-- Right column -->
            <div class="col-md-6">
              <div class="mb-3">
                {{ form.priority|as_crispy_field }}
              </div>

              <div class="mb-3">
                {{ form.task_type|as_crispy_field }}
              </div>

              <div class="mb-3">
                {{ form.assignees|as_crispy_field }}
              </div>
            </div>
          </div>

          <div class="d-flex justify-content-between mt-4">
            <button type="submit" class="btn btn-primary">
              {{ object|yesno:"Save,Create" }}
            </button>
            <a href="{% url 'tasks:index' %}" class="btn btn-secondary">Cancel</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/tasks/task_type_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="content">
    <h2 class="content-title">
      {% if form.instance.pk %}
        Edit Task Type
      {% else %}
        Create New Task Type
      {% endif %}
    </h2>

    <div class="card">
      <div class="card-body">
        <form method="post" class="tasktype-form">
          {% csrf_token %}
          
          <div class="mb-3">
            {{ form.name|as_crispy_field }}
          </div>

          <div class="d-flex justify-content-between mt-4">
            <button type="submit" class="btn btn-primary">
              {{ object|yesno:"Update,Create" }}
            </button>
            <a href="{% url 'tasks:task-type-list' %}" class="btn btn-secondary">Cancel</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/tasks/tasktype_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="content">
    <h2 class="content-title">Delete Task Type</h2>
    <p>Are you sure you want to delete the task type "{{ tasktype.name }}"?</p>
    <form method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger" style="white-space: nowrap;">Yes</button>
      <a href="{% url 'tasks:task-type-list' %}" class="btn btn-secondary" style="white-space: nowrap;">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/tasks/tasktype_list.html
{% extends "base.html" %}

{% block content %}
  <div class="content">
    <div class="d-flex justify-content-between align-items-center mb-3">
      <h2 class="content-title">Task Types</h2>
      <a href="{% url 'tasks:task-type-create' %}" class="btn btn-primary tasktype-create-btn">
  Add
</a>
    </div>

    <table class="tasktype-table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for tasktype in tasktype_list %}
          <tr>
            <td>{{ tasktype.name }}</td>
            <td class="col-2">
              <a href="{% url 'tasks:task-type-update' tasktype.pk %}" class="btn btn-sm tasktype-edit-btn">Edit</a>
              <a href="{% url 'tasks:task-type-delete' tasktype.pk %}" class="btn btn-sm tasktype-delete-btn">Delete</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/tasks/worker_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="content">
    <h2 class="content-title">Delete Worker</h2>
    <p>Are you sure you want to delete the worker "{{ worker.username }}"?</p>
    <form method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger" style="white-space: nowrap;">Yes</button>
      <a href="{% url 'tasks:worker-list' %}" class="btn btn-secondary" style="white-space: nowrap;">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/tasks/worker_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Worker: {{ worker.username }}
  </h1>

  <p><strong>First name:</strong> {{ worker.first_name|default:"-" }}</p>
  <p><strong>Last name:</strong> {{ worker.last_name|default:"-" }}</p>
  <p><strong>Email:</strong> {{ worker.email|default:"-" }}</p>
  <p><strong>Position:</strong> {{ worker.position }}</p>

  <div class="ml-3">
    <h4>Tasks</h4>

    {% for task in worker.assigned_tasks.all %}
      <hr>
      <p><strong>Task:</strong> {{ task.name }}</p>
      <p><strong>Task Status:</strong> <i>{{ task.is_complete|yesno:"Done,Not Done" }}</i></p>

    {% empty %}
      <p>No tasks!</p>
    {% endfor %}

  </div>
{% endblock %}

templates/tasks/worker_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="content">
    <h2 class="content-title">
      {% if form.instance.pk %}
        Edit Worker
      {% else %}
        Create New Worker
      {% endif %}
    </h2>

    <div class="card">
      <div class="card-body">
        <form method="post" class="worker-form">
          {% csrf_token %}
          
          <div class="col-3">
            {{ form.username|as_crispy_field }}
          </div>

          <div class="col-3">
            {{ form.first_name|as_crispy_field }}
          </div>

          <div class="col-3">
            {{ form.last_name|as_crispy_field }}
          </div>

          <div class="col-3">
            {{ form.password1|as_crispy_field }}
          </div>

          <div class="col-3">
            {{ form.password2|as_crispy_field }}
          </div>

          <div class="col-3">
            {{ form.email|as_crispy_field }}
          </div>

          <div class="col-3">
            {{ form.position|as_crispy_field }}
          </div>

          <div class="d-flex justify-content-between col-3">
            <button type="submit" class="btn btn-primary">
              {{ object|yesno:"Save,Create" }}
            </button>
            <a href="{% url 'tasks:worker-list' %}" class="btn btn-secondary">Cancel</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/tasks/worker_list.html
{% extends "base.html" %}

{% block content %}
  <div class="content">
    <div class="d-flex justify-content-between align-items-center mb-3">
      <h2 class="content-title">Workers</h2>
      <a href="{% url 'tasks:worker-create' %}" class="btn btn-primary worker-create-btn">
        Add
      </a>
    </div>

    <table class="worker-table">
      <thead>
        <tr>
          <th>Username</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Email</th>
          <th>Position</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for worker in worker_list %}
          <tr>
            <td><a href="{% url "tasks:worker-detail" pk=worker.id %} " style="text-decoration: none; color: black">{{ worker.username }}</a></td>
            <td>{{ worker.first_name|default:"-" }}</td>
            <td>{{ worker.last_name|default:"-" }}</td>
            <td>{{ worker.email|default:"-" }}</td>
            <td>{{ worker.position.name|default:"-" }}</td>
            <td>
              <a href="{% url 'tasks:worker-update' worker.pk %}" class="btn btn-sm worker-edit-btn">Edit</a>
              <a href="{% url 'tasks:worker-delete' worker.pk %}" class="btn btn-sm worker-delete-btn">Delete</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}